### ISSUE TITLE
Export & Record endpoint

### ISSUE THREAD

**Issue by dragonlee97** [dragonlee97/ELT_pipeline2#1]
https://github.com/dragonlee97/meero_case_study/blob/c79aa67db8e6d7c2e45933685ea8770fde47db05/dags/helpers/utils.py#L18

Hello @erokaz, c'était un palsir de discuters sur les points techniques avec toi :)

A la suite de notre échange, j'ai encore zoomé un peu sur la partie api et je vourdrais te partager quelques informations que j'ai retrouvé:
- Il y a seulement deux valeurs distinctives (2020-06-11, 2020-07-25)dans le champs 'updated_date' avec 60000+ et 20000+ de lignes respectivement,  donc les deux passent la limite de 10000. Effectivement, on peut se servir de l'autre champs date 'Date last review', mais il est pes complète. Si il y avait un timestamp assez granulaire, je ne manquerais pas réduire la volume du payload de la résponse. Segmenter par **id** est une solution faisable si on précise l'intervalle. 
<img width="1077" alt="Screenshot 2024-02-28 at 08 39 10" src="https://github.com/dragonlee97/meero_case_study/assets/34571516/f9c017e9-71ce-49ac-80ed-c4dc2797b8ef">

- Sur la doc, J'avais vu la suggestion d'utiliser l'endpoint export. Et en fait, on peut aussi filtrer sur les résultats avec l'endpoint exports (c'est ce que j'ai fait pour la France). En réalité, je suppose qu'on peut adopter la même logique d'upsert pour airbnb listing au lieu de tout charger chaque jour.
<img width="955" alt="Screenshot 2024-02-28 at 00 39 30" src="https://github.com/dragonlee97/meero_case_study/assets/34571516/241f6416-3aa8-47e4-9bea-0e8e50d507ec">
<img width="1133" alt="Screenshot 2024-02-28 at 00 40 30" src="https://github.com/dragonlee97/meero_case_study/assets/34571516/62e24629-720e-4ee4-94dc-c3d16928e9b6">

**Comment by erokaz** [comment]
> https://github.com/dragonlee97/meero_case_study/blob/c79aa67db8e6d7c2e45933685ea8770fde47db05/dags/helpers/utils.py#L18
> 
> Hello @erokaz, c'était un palsir de discuters sur les points techniques avec toi :)
> 
> A la suite de notre échange, j'ai encore zoomé un peu sur la partie api et je vourdrais te partager quelques informations que j'ai retrouvé:
> 
> * Il y a seulement deux valeurs distinctives (2020-06-11, 2020-07-25)dans le champs 'updated_date' avec 60000+ et 20000+ de lignes respectivement,  donc les deux passent la limite de 10000. Effectivement, on peut se servir de l'autre champs date 'Date last review', mais il est pes complète. Si il y avait un timestamp assez granulaire, je ne manquerais pas réduire la volume du payload de la résponse. Segmenter par **id** est une solution faisable si on précise l'intervalle.
> 
> <img alt="Screenshot 2024-02-28 at 08 39 10" width="1077" src="https://private-user-images.githubusercontent.com/34571516/308378962-f9c017e9-71ce-49ac-80ed-c4dc2797b8ef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxMTYwNzksIm5iZiI6MTcwOTExNTc3OSwicGF0aCI6Ii8zNDU3MTUxNi8zMDgzNzg5NjItZjljMDE3ZTktNzFjZS00OWFjLTgwZWQtYzRkYzI3OTdiOGVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI4VDEwMjI1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRjMDczYjc5YTJkMjIwMTk4ZTZiOWMzZTJlN2VkYjliMmIwMmFmYjdjMTcwZmY0NjgyNWEzZmZjMjIwNjM0ZmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mHCtG1WxR8V5duiZCH9anNIqAzVgYMdSZwvlgNpx-DQ">
> * Sur la doc, J'avais vu la suggestion d'utiliser l'endpoint export. Et en fait, on peut aussi filtrer sur les résultats avec l'endpoint exports (c'est ce que j'ai fait pour la France). En réalité, je suppose qu'on peut adopter la même logique d'upsert pour airbnb listing au lieu de tout charger chaque jour.
> 
> <img alt="Screenshot 2024-02-28 at 00 39 30" width="955" src="https://private-user-images.githubusercontent.com/34571516/308378529-241f6416-3aa8-47e4-9bea-0e8e50d507ec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxMTYwNzksIm5iZiI6MTcwOTExNTc3OSwicGF0aCI6Ii8zNDU3MTUxNi8zMDgzNzg1MjktMjQxZjY0MTYtM2FhOC00N2U0LTliZWEtMGU4ZTUwZDUwN2VjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI4VDEwMjI1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY1ZDdkNWZmNTQ2OTk1ZWUyNjRiNDZhZTZlNjQ2OGM5ZjcyY2Y2YTVhYjg1OTMxZDdmM2I5ZWVmYjEyZjBkODkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ioq8ddQb3Qjw5wFjDjJ-JU6sKkM6Vhxgcda8_OxfXzs"> <img alt="Screenshot 2024-02-28 at 00 40 30" width="1133" src="https://private-user-images.githubusercontent.com/34571516/308378563-62e24629-720e-4ee4-94dc-c3d16928e9b6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxMTYwNzksIm5iZiI6MTcwOTExNTc3OSwicGF0aCI6Ii8zNDU3MTUxNi8zMDgzNzg1NjMtNjJlMjQ2MjktNzIwZS00ZWU0LTk0ZGMtYzNkMTY5MjhlOWI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI4VDEwMjI1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYyMjA5MjM5YWEzODM0Y2Y0ZDk1ZjE1YjhiOTU2YjUzMDM2ZjRkYmQxMmVmNzNkNzUxMzU2MjAyYWE5Y2RlZjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8gBhD4FZnE2yeYqjVatOXuc8Er67AJphlWwKpI4wChs">

Hello, oui désolé je me suis trompé hier, effectivement il faut utiliser l'ID !
